services:
  frontend:
    build:
      context: ./ochiga-frontend       # ðŸ‘ˆ everything lives here, including Dockerfile
      dockerfile: Dockerfile
    container_name: ochiga-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ochiga-frontend:/app
    working_dir: /app
    command: npm run start
    depends_on:
      - backend

  backend:
    build:
      context: ./ochiga-backend-for-estate-and-smart-home
      dockerfile: Dockerfile
    container_name: ochiga-backend
    ports:
      - "4000:4000"
    working_dir: /app
    volumes:
      - ./ochiga-backend-for-estate-and-smart-home:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
